import streamlit as st
st.set_page_config(page_title="Multimodal RAG Chat App", page_icon=":speech_balloon:", layout="wide")

# Title
st.title(":rainbow[**🌟 Welcome to the Multimodal RAG Chat App! 🌟**]")

# Introduction Section
st.markdown("""
    **Discover the future of interactive conversation!**  
    Our cutting-edge Multimodal Retrieval-Augmented Generation (RAG) Chat App leverages the power of the **Qwen 2.5** open-source model to provide intelligent, context-aware responses based on user queries.  

    This application excels in understanding various input formats, including text, images, and documents, ensuring a comprehensive interaction experience. With integrated image handling features powered by **Florence**, users can upload and inquire about visual content, making the interaction not just textual but also rich in imagery.

    ## Key Features:
    - **Multimodal Understanding**: Seamlessly interact with text and images for a complete user experience.
    - **Intelligent Responses**: Harnessing the capabilities of the Qwen 2.5 model, our app delivers contextually relevant answers.
    - **Florence Integration**: Utilize advanced image processing and understanding features for effective content extraction and interaction.
    - **OpenAI RAG Integration**: Experience enhanced conversations with RAG capabilities from OpenAI, making your interactions even more insightful.

    ## Why Choose Our App?
    - **User-Friendly Interface**: Designed with simplicity and usability in mind, anyone can start chatting right away!
    - **Open-Source Excellence**: Benefit from the power of community-driven development with our open-source foundations.
    - **Versatile Applications**: Ideal for education, research, and everyday inquiries, making it a perfect tool for various use cases.

    Dive into the world of **Multimodal AI** with us and transform your conversations into enriched, engaging experiences!
""")

# Add an Image Section
st.image("https://www.anthropic.com/_next/image?url=https%3A%2F%2Fwww-cdn.anthropic.com%2Fimages%2F4zrzovbb%2Fwebsite%2F45603646e979c62349ce27744a940abf30200d57-3840x2160.png&w=3840&q=75", caption="Enhance Your Interaction with Multimodal AI", use_column_width=True)

# Additional Information Section
st.subheader("How to Use the App:")
st.markdown("""
1. **Upload Files**: Drag and drop your PDFs, DOCX, or images into the app.
2. **Ask Questions**: Type in your queries related to the content you uploaded.
3. **Receive Responses**: Get context-aware answers generated by our powerful models.
4. **Explore Further**: Engage in further inquiries, enriching your understanding and interaction.

For more information, visit our [documentation](#) or contact us for support.
""")

# Footer
st.markdown("""
    **Join the Community!**  
    Become a part of our open-source community and contribute to the future of AI-driven interactions.
    
    ---
    © 2024 Multimodal RAG Chat App | All Rights Reserved
""")
